DROP TABLE IF EXISTS Employee;

CREATE TABLE Employee (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  ssn VARCHAR(20) NOT NULL,
  mobile VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT  NULL
);